services:
  client:
    container_name: APIs2db_dev_client
    build: ./client
    image: debug_client
    ports: 
      - 8080:8080
    working_dir: /code
    volumes:
      - type: bind
        source: ./client
        target: /code
    command: [ "http-server" ]
  api:
    container_name: APIs2db_dev_api
    ports: 
      - 3000:3000
    environment: 
      - PGUSER=anaxz
      - PGHOST=db
      - PGPASSWORD=pass
      - PGDATABASE=cats
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run seedDev && npm run dev"

  db:
    container_name: APIs2db_dev_db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=cats
      - POSTGRES_USER=anaxz
      - POSTGRES_PASSWORD=pass
volumes:
  dbdata:
networks: 
  default:
    name: debug_api
